apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-uservice
spec:
  selector:
    matchLabels:
      uservice: rest-uservice
  replicas: 1
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        uservice: rest-uservice
      spec:
      containers:
        - name: rest-uservice
          image:
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "500Mi"
              cpu: "256m"
            limits:
              memory: "500Mi"
              cpu: "256m"
          readinessProbe:
            httpGet:
              path: "/actuator/health"
              port: 8080
            initialDelaySeconds: 100
            failureThreshold: 1
            timeoutSeconds: 10
            periodSeconds: 30
          livenessProbe:
            httpGet:
              path: "/actuator/health"
              port: 8080
            initialDelaySeconds: 200
            failureThreshold: 3
            timeoutSeconds: 10
            periodSeconds: 10
          startupProbe:
            httpGet:
              path: "/actuator/health"
              port: 8080
            failureThreshold: 60
            periodSeconds: 10

