apiVersion: v1
kind: Service
metadata:
  name: <SERVICE_NAME>
  namespace: <ENVIRONMENT>
  labels:
    uservice: <SERVICE_NAME>
    version: "<SERVICE_VERSION>"
spec:
  ports:
    - name: http
      port: 8080
  selector:
    uservice: <SERVICE_NAME>
    version: "<SERVICE_VERSION>"
