name: CI

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:

  Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: aws-actions/setup-sam@v1
    - uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build Snapshot
      run: |
        cd initial
        export CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain test --domain-owner ${{ secrets.AWS_ACCOUNT_ID }} --query authorizationToken --output text`
        bash ./gradlew -Pbuild_target=SNAPSHOT clean build
    - name: Login to ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    - name: Docker Build & Push
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      run: |
        cd initial
        export SERVICE_NAME=`echo "${{ github.repository }}" | awk -F "/" '{print $2}'`
        export VERSION=`bash ./gradlew -Pbuild_target=SNAPSHOT -q properties | grep version | sed -e "s@version: @@g"`
        export SERVICE_CODE=`echo "$VERSION" | cut -d '-' -f1`
        export IMAGE_NAME="$ECR_REGISTRY/$SERVICE_NAME:$SERVICE_CODE.${{ github.sha }}"
        docker build -t $ECR_REGISTRY/$SERVICE_NAME:$SERVICE_CODE.${{ github.sha }} .
#        docker push $ECR_REGISTRY/$SERVICE_NAME:$SERVICE_CODE.${{ github.sha }}
        
  DeployToDev:
    runs-on: ubuntu-latest
    needs: Build
    concurrency: deploy
    environment: dev
    steps:
      - uses: actions/checkout@v3
      - uses: azure/setup-kubectl@v2.0
      - uses: mikefarah/yq@master
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Clone Common Repo
        run: |
          eval `ssh-agent -s`
          echo "{{ secrets.SSH_KEY }}" | ssh-add -
          ls
      - name: Deploy to EKS
        run: ./deploy.sh
        env:
          ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
          COMMIT_HASH: ${{ github.sha }}
          ENVIRONMENT: "dev"




