name: CI

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        java-version: 11
        cache: 'gradle'
    - name: Build Snapshot
      run: bash ./initial/gradlew -Pbuild_target=SNAPSHOT clean build

