name: PR-BUILD

on:
  workflow_call:
  pull_request:
    branches: [ development ]

jobs:
  PR-CHECK:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: PR-BUILD
      run: |
        cd initial
        export CHANGE_ID=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
        bash ./gradlew -Pbuild_target=SNAPSHOT clean build jacocoTestReport spotlessApply spotbugsMain
        bash ./gradlew sonarqube -Dsonar.pullrequest.branch=${{ github.head_ref }} -Dsonar.pullrequest.base=${{ github.base_ref } -Dsonar.pullrequest.key=${CHANGE_ID} showSonarQubeLink --info
