name: reusable-workflow

on:
  workflow_call:
    inputs:
      module:
        required: true
        type: string
jobs:
  Production-Release:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Create Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}

  Deploy-To-Prod:
    runs-on: ubuntu-latest
    needs: Production-Release
    environment: prod
    permissions:
      id-token: write
      issues: read
      checks: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: azure/setup-kubectl@v2.0
      - uses: mikefarah/yq@master
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          role-session-name: git-actions-pipeline
          aws-region: us-east-1
      - name: Clone Common Repo
        run: |
          eval `ssh-agent -s`
          ssh-add - <<< "${{ secrets.SSH_KEY }}"
          git clone git@github.com:ksgnextuple/common-deploy-scripts.git
      - name: Deploy to EKS
        run: ./common-deploy-scripts/scripts/deploy.sh
        env:
          ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
          COMMIT_HASH: ${{ github.sha }}
          ENVIRONMENT: "prod"
          PROJECT: ${{ inputs.module }}