name: RELEASE

on:
  push:
    branches:
      - master
jobs:
  release-on-push:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
        run: |
          cd initial
          export VERSION=`bash ./gradlew -Pbuild_target=SNAPSHOT -q properties | grep version | sed -e "s@version: @@g"`
      - uses: rymndhng/release-on-push-action@master
        with:
          tag_prefix: "v"
          release_name: ${VERSION}-RELEASE

